# .gitlab-ci.yml

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t my-api-image .

deploy:
  stage: deploy
  image: google/cloud-sdk
  script:
    - gcloud container clusters get-credentials my-cluster --zone=my-zone --project=my-project
    - kubectl apply -f deployment.yaml
